# Site settings
title: OpenMessaging
email: yukon@apache.org
description: |
  OpenMessaging is a cloud-oriented and vendor-neutral open standard for messaging, providing industry guidelines for areas such as finance, e-commerce, IoT and Big Data and oriented toward furthering messaging and streaming applications across heterogeneous systems and platforms.
baseurl: "" # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown

# Syntax highlighting settings
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Use "pretty" URLs, i.e. /docs instead of /docs.html
permalink: pretty

paginate: 4
paginate_path: "blog/page:num"

plugins:
- jekyll-paginate

include:
- _internal

defaults:
- scope:
    path: docs
  values:
    layout: docs