name: Ruby Gem

on:
  push:
    branches: [ source ]


jobs:
  build:
    name: Auto publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.4.1
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.4.1

    - name: build
      run: |
        make setup
        ls -l
